stash/GetLinksForFile: Fix unhashable type: 'list'
When calling Stash.GetLinksForFile we would get following exception:
    TypeError: unhashable type: 'list'
This is caused by the usage of functools.cache. To fix it we can simply
convert self.__list to a frozenset, which is hashable.

Additionally I replaced _Stash__map usage in test_bbappends, that I
added in previous commit to use fixed GetLinksForFile.

Signed-off-by: Michal Sieron <michalwsieron@gmail.com>